### ISSUE TITLE
Support Private Github Repos

### ISSUE THREAD

**Issue by michaelhofrichter** [SuffolkLITLab/ALKiln#417]
If I'm pulling a private Github repo into the playground, it works if my url for the package includes my github personal access token per https://docassemble.org/docs/development.html#githubprivate. If I just write my private package link, Docassemble can still query the appropriate branches, but it can't install them.

**Comment by michaelhofrichter** [comment]
perhaps use the `git@github.com:` link instead -- that doesn't require the detail
`GitHub packages have two "URLs." One is the one that begins with https://github.com.  The other is the one that looks like git@github.com:jhpyle/docassemble-somepackage.git.  You can find this "URL" using the "Code" button in GitHub when you are looking at a repository.
You can use the latter format for cloning a private repo in the Playground "pull" interface.`

**Comment by plocket** [comment]
We'll need to handle this in the setup script in `puppeteer-utils.js`. We'll need to parse out the GitHub repo info and replace it with that prefix and the suffix. This should supposedly work for public repositories as well.

**Comment by plocket** [comment]
Blocked by a docassemble bug that doesn't let you pull a private repo into an empty da Project. That's on the radar to be fixed, but we're not sure how long it will take. In the meantime there's this work around:

> in the meantime you can get around it if you just create a "package" (doesn't matter what it's called or what it has in it), and then do the "pull."

I'm going to go ahead and do it because it's unclear when the patch will be out and we want people to be able to use this. It will slow down everyone's tests a fraction, but it's temporary.

**Comment by plocket** [comment]
Note: for a private repo, a developer needs to integrate the testing account with a GitHub account that has permissions for that repository.

**Comment by plocket** [comment]
Welp, the workaround we did is not necessary for updated docassemble servers:

https://docassemble.org/docs/changelog.html `1.3.9 - 2021-12-11`
> Fixed issue where GitHub SSH only worked during a Playground pull if there was an active package.

That said, not everyone is going to update to that for a while, so it may be worth keeping this temporary fix in place for now. Since one of our next steps will be to utilize the API for all this stuff, it may be worth just keeping this here and getting rid of it, along with other stuff, at v4.

**Comment by plocket** [comment]
`1.3.9` commit that I believe created this API is at https://github.com/jhpyle/docassemble/commit/8b3ef3da4a1dfd2d91d9c1fdc390dbc84f4840f9#diff-4c8bf136c393acf44c18098d2b935b3a005636e57574530acffdf552432360faR18579. Should check how private repos are handled there.
