### ISSUE TITLE
Can developers store their own version of Kiln to use and update selectively?

### ISSUE THREAD

**Issue by rpigneri-vol** [SuffolkLITLab/ALKiln#437]
We have a customer ask to move the Kiln code/GitHub action from the developer's repo to the DA server itself.  This story concerns how feasible it is to implement a way to locally control the Kiln source.

**Comment by plocket** [comment]
Restating a tad - can we allow a developer to choose to store the code of Kiln themselves, pulling in new versions of the code when desired.

It doesn't actually need to be on the DA server, though that would be convenient. It could be on GitHub.

Context:
Though people can freeze their version of Kiln at a patch version, npm doesn't guarantee versions don't change. Currently, developers can at least fork it and put their own code on npm, then refer to that package instead of our own. We haven't yet discussed whether that's secure enough or not, but in the meantime, we're looking into whether we can give them more control than that.

Note: It occurs to me that the API key will only be used in `setup` and `takedown`. We may add another repo (I know) to the current ones that just stores those. It would make it easier for people to check for changes to the code that uses the API key.

**Comment by plocket** [comment]
Most recent thought: we could help them make a submodule: https://git-scm.com/book/en/v2/Git-Tools-Submodules. That’s where you have one git repo inside another git repo. From what I can see, they would store the code in their repo and be able to update selectively.

Their package.json could look a lot more like ALKiln's own package.json, referring to local files.

**Comment by plocket** [comment]
With our current plan, I'm not sure it would work. I'm not sure how they'd reference the action fi ti was part of the submodule. I think actions need to be in the root of a project. They might need to make their own action.yml and subscribe to that action in their workflow. They would then need to manually manage and change that action and update its tags, as well as the reference in that workflow.

Maybe it would be simpler to show them how to make their own workflow that does the same thing as our action. I'm still not sure they could get at the package.json in the submodule, but maybe that's not as hard as I think for some reason... Or maybe we'd have them make their own package.json that just referenced our package.json scripts... Would definitely need some experimentation.

**Comment by plocket** [comment]
Since we can tell people how to pin the action version to a commit, we may end up taking this out of milestone v4.

**Comment by plocket** [comment]
Users can pin actions using commit SHA through GitHub natively in a workflow, which is safe, and [pin npm versions](https://assemblyline.suffolklitlab.org/docs/alkiln/writing/#optional-inputs), which is as safe as it can be (despite confusing conversations), and should use those 2 together. They can copy our actions to have their own local actions. They have a way to run [ALKiln in the Playground](https://assemblyline.suffolklitlab.org/docs/alkiln/setup#diy-details) and can use specific patch versions of that. They can clone the repo, publish their own version on npm and use that instead. I think their bases are covered at this point.
